import { createHash } from 'node:crypto';

import {
  digestBytes,
  encodeLf,
  GENERATED_WARNING,
} from '../adapters/render-shared.js';

const GENERATED_MARKER = `<!-- ${GENERATED_WARNING} -->`;
const CONTENT_HASH_RE = /<!--\s*Content hash:\s*(sha256:[a-f0-9]{64})\s*-->/;

export type DriftReason = 'missing_acs_header' | 'body_mismatch';

export type TargetAssessment =
  | { kind: 'missing' }
  | { kind: 'clean' }
  | { kind: 'replaceable' }
  | { kind: 'drifted'; reason: DriftReason };

/** Normalize text to LF with a trailing newline for stable comparisons. */
export function normalizeGeneratedText(text: string): string {
  return Buffer.from(encodeLf(text)).toString('utf8');
}

/** SHA-256 digest of file bytes, formatted as `sha256:<hex>`. */
export function fileDigest(contents: string): string {
  return digestBytes(encodeLf(contents));
}

/** SHA-256 hex (no prefix) for binding preview target hashes. */
export function fileHashHex(contents: string | Uint8Array): string {
  const bytes = typeof contents === 'string' ? encodeLf(contents) : contents;
  return createHash('sha256').update(bytes).digest('hex');
}

/** Parse ACS generation headers from a target file, if present. */
export function parseAcsHeaders(
  contents: string,
): { contentHash: string } | undefined {
  if (!contents.includes(GENERATED_MARKER) && !contents.includes('Generated by agent-context-sync')) {
    return undefined;
  }
  const match = contents.match(CONTENT_HASH_RE);
  if (match === null || match[1] === undefined) return undefined;
  return { contentHash: match[1] };
}

/** Extract the embedded Content hash from generated text. */
export function embeddedContentHash(contents: string): string | undefined {
  return parseAcsHeaders(contents)?.contentHash;
}

/**
 * Classify a business-repo target relative to newly generated bytes.
 *
 * - missing → safe to create
 * - byte-identical → clean no-op
 * - ACS headers present with a different Content hash → prior generation, replaceable
 * - ACS headers present with the same Content hash but different bytes → body drift
 * - no ACS headers → unmanaged drift
 */
export function assessTarget(
  current: string | undefined,
  generatedText: string,
): TargetAssessment {
  if (current === undefined) return { kind: 'missing' };

  const normalizedCurrent = normalizeGeneratedText(current);
  const normalizedGenerated = normalizeGeneratedText(generatedText);
  if (normalizedCurrent === normalizedGenerated) return { kind: 'clean' };

  const meta = parseAcsHeaders(normalizedCurrent);
  if (meta === undefined) {
    return { kind: 'drifted', reason: 'missing_acs_header' };
  }

  const generatedHash = embeddedContentHash(normalizedGenerated);
  if (generatedHash !== undefined && meta.contentHash === generatedHash) {
    return { kind: 'drifted', reason: 'body_mismatch' };
  }

  return { kind: 'replaceable' };
}
