import { createHash } from 'node:crypto';
import type { CompiledContext, CompiledSection } from '../compiler/compile.js';
import { compareCodeUnits } from '../domain/compare.js';
import type { KnowledgeEntry } from '../domain/model.js';
import type { ContentDigest, RenderedFile } from './adapter.js';

export const GENERATED_WARNING =
  'Generated by agent-context-sync. Do not edit directly; capture changes through the sync workflow.';

export function digestBytes(bytes: Uint8Array): ContentDigest {
  return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
}

export function encodeLf(text: string): Uint8Array {
  const normalized = text.replace(/\r\n?/g, '\n');
  const withNewline = normalized.endsWith('\n') ? normalized : `${normalized}\n`;
  return new Uint8Array(Buffer.from(withNewline, 'utf8'));
}

export function knowledgeContentHash(entries: readonly KnowledgeEntry[]): ContentDigest {
  const payload = [...entries]
    .sort((left, right) => compareCodeUnits(left.id, right.id))
    .map((entry) => `${entry.id}\n${entry.statement}\n${entry.reason}`)
    .join('\n\n');
  return digestBytes(encodeLf(payload));
}

export function stableScopeId(paths: readonly string[]): string {
  const key = [...paths].sort(compareCodeUnits).join('\n');
  const digest = createHash('sha256').update(key).digest('hex').slice(0, 16);
  return `scope-${digest}`;
}

export function pathGroupKey(paths: readonly string[]): string {
  return [...paths].sort(compareCodeUnits).join('\n');
}

/**
 * Derive a nested directory from path globs (e.g. `src/auth/**` → `src/auth`).
 * Falls back to `.agents/<stable-scope-id>` when the pattern is not directory-like.
 */
export function directoryForPathGlobs(paths: readonly string[]): string {
  const primary = [...paths].sort(compareCodeUnits)[0] ?? '';
  let candidate = primary
    .replace(/\\/g, '/')
    .replace(/\/\*\*$/, '')
    .replace(/\/\*$/, '')
    .replace(/\*\*$/, '')
    .replace(/\*$/, '')
    .replace(/\/$/, '');
  if (
    candidate.length === 0
    || candidate.includes('*')
    || candidate.includes('?')
    || candidate.includes('[')
    || candidate.startsWith('/')
    || /^[A-Za-z]:[\\/]/.test(candidate)
  ) {
    return `.agents/${stableScopeId(paths)}`;
  }
  return candidate;
}

export function formatEntryBlock(entry: KnowledgeEntry): string {
  const lines = [`- ${entry.statement.trim()}`];
  const reason = entry.reason.trim();
  if (reason.length > 0) {
    lines.push(`  - Reason: ${reason}`);
  }
  return lines.join('\n');
}

export function formatSection(section: CompiledSection): string {
  const blocks = section.entries.map((entry) => formatEntryBlock(entry));
  return [`## ${section.title}`, '', ...blocks].join('\n');
}

export function buildHeader(compiled: CompiledContext, contentHash: ContentDigest): string {
  const lines = [
    `<!-- ${GENERATED_WARNING} -->`,
  ];
  if (compiled.workspace_id !== undefined) {
    lines.push(`<!-- Workspace ID: ${compiled.workspace_id} -->`);
  }
  if (compiled.context_head !== undefined) {
    lines.push(`<!-- Context commit: ${compiled.context_head} -->`);
  }
  lines.push(`<!-- Content hash: ${contentHash} -->`);
  return lines.join('\n');
}

export function collectEntries(sections: readonly CompiledSection[]): KnowledgeEntry[] {
  return sections.flatMap((section) => section.entries);
}

export function toRenderedFile(
  relativePath: string,
  text: string,
  sourceKnowledgeIds: readonly string[],
): RenderedFile {
  const bytes = encodeLf(text);
  return {
    relativePath,
    bytes,
    sha256: digestBytes(bytes),
    sourceKnowledgeIds: [...sourceKnowledgeIds].sort(compareCodeUnits),
  };
}

export function sortRenderedFiles(files: RenderedFile[], rootPath: string): RenderedFile[] {
  return [...files].sort((left, right) => {
    if (left.relativePath === rootPath) return -1;
    if (right.relativePath === rootPath) return 1;
    return compareCodeUnits(left.relativePath, right.relativePath);
  });
}

export function groupPathEntries(
  pathSection: CompiledSection | undefined,
): Map<string, KnowledgeEntry[]> {
  const groups = new Map<string, KnowledgeEntry[]>();
  if (!pathSection) return groups;
  for (const entry of pathSection.entries) {
    const key = pathGroupKey(entry.applies_to.paths);
    const existing = groups.get(key);
    if (existing) existing.push(entry);
    else groups.set(key, [entry]);
  }
  for (const entries of groups.values()) {
    entries.sort((left, right) => compareCodeUnits(left.id, right.id));
  }
  return groups;
}
